### ISSUE TITLE
Duplicated coordinates

### ISSUE THREAD

**Issue by alexahn917** [Sparen/Summer2016_Network#22]
Need to handle cases where same coordinates are repeated in an edge object

**Comment by Sparen** [comment]
As of 978d18a2769abdbf14ca5ff50e8072f6a16c744f, orthogonal corners sometimes appear. Cause unknown.

**Comment by Sparen** [comment]
the new changes also cause some strange things to happen with edges in general - this needs to be looked into (in case some midpoints are simply being dropped entirely)

**Comment by alexahn917** [comment]
I will look further into it
