### ISSUE TITLE
resetEdgeToLoop needs to take overlap into account

### ISSUE THREAD

**Issue by Sparen** [Sparen/Summer2016_Network#26]
As of now, resetEdgeToLoop still does not take overlaps into account, resulting in poor user experience when it overlaps with other edges.

**Comment by trileica** [comment]
I tried to come up with an idea, but all I can think is something very troublesome and tedious.

**Comment by trileica** [comment]
I think one convenient way is to make two more midpoints: from the source stub, either go up or down to the buffer region between each row of nodes, then go left or right directly until reaching outside of the whole node set, then connect to the target stub.
